export enum USER_ACTION_TYPES {
  CHECK_USER_SESSION = 'CHECK_USER_SESSION',
  GOOGLE_SIGN_IN_REQUEST = 'GOOGLE_SIGN_IN_REQUEST',
  EMAIL_SIGN_IN_REQUEST = 'EMAIL_SIGN_IN_REQUEST',
  SIGN_IN_SUCCESS = 'SIGN_IN_SUCCESS',
  SIGN_IN_FAILED = 'SIGN_IN_FAILED',
  SIGN_UP_REQUEST = 'SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',
  SIGN_OUT_REQUEST = 'SIGN_OUT_REQUEST',
  SIGN_OUT_SUCCESS = 'SIGN_OUT_SUCCESS',
  SIGN_OUT_FAILED = 'SIGN_UP_FAILED',
}
